#!/usr/bin/env tsx
/** reels:vocab — regenerate docs/VOCABULARY.md from the registries (never hand-edit it). */
import { writeFileSync } from 'node:fs';
import path from 'node:path';
import { ACTIONS } from '../src/cast/actions';
import { LOOKS } from '../src/cast/looks';
import { CUES } from '../src/audio/registry';
import { GENERIC_LENSES, LENS_SUBJECTS } from '../src/camera/lenses';
import { MOVE_IDS } from '../src/camera/moves';
import { EFFECTS } from '../src/effects/registry';
import { FORMATS } from '../src/engine/formats';
import { GRAPHICS, TEXT_STYLES } from '../src/graphics/registry';
import { TRANSITIONS } from '../src/transitions/registry';
import { WORLDS } from '../src/worlds/registry';
import { MOMENT_BEATS, MOMENT_ROLES } from '../src/worlds/football/choreography';
import { REELS_ROOT } from './lib/remotion';

const L: string[] = ['# HNC content vocabulary', '', '_Generated by `npm run reels:vocab` from the registries — do not edit by hand._', ''];
const table = (head: string[], rows: string[][]) => {
  L.push(`| ${head.join(' | ')} |`, `|${head.map(() => '---').join('|')}|`, ...rows.map((r) => `| ${r.join(' | ')} |`), '');
};
L.push('## Formats', '');
table(['id', 'size', 'use'], Object.values(FORMATS).map((f) => [`\`${f.id}\``, `${f.width}×${f.height}`, f.label]));
L.push('## Worlds', '');
for (const w of Object.values(WORLDS)) {
  L.push(`### \`${w.id}\` (${w.kind})`, '', w.summary, '');
  if (Object.keys(w.params).length) L.push('Params (`set`): ' + Object.entries(w.params).map(([k, v]) => `\`${k}\` — ${v}`).join('; '), '');
  if (Object.keys(w.marks).length) L.push('Marks: ' + Object.entries(w.marks).map(([k, m]) => `\`${k}\` (${m.posture})`).join(', '), '');
  const subj = [...Object.keys(w.props), ...Object.keys(w.lights).map((l) => `${l} (light)`), ...Object.keys(w.surfaces).map((s) => `${s} (screen)`)];
  if (subj.length) L.push('Subjects: ' + subj.map((s) => `\`${s}\``).join(', '), '');
  if (w.lensIds.length) L.push('World lenses / moves: ' + w.lensIds.map((s) => `\`${s}\``).join(', '), '');
  if (w.ambience) L.push(`Ambience bed: \`${w.ambience}\``, '');
  if (w.effects?.length) L.push('World effects: ' + w.effects.map((e) => `\`${e}\``).join(', '), '');
  if (w.id === 'football') {
    for (const [m, roles] of Object.entries(MOMENT_ROLES)) L.push(`Moment \`${m}\`: roles ${roles.map((r) => `\`${r}\``).join(', ')}; beats ${Object.keys(MOMENT_BEATS[m]).map((b) => `\`moment:${b}\``).join(', ')}`, '');
  }
}
L.push('## Camera lenses (generic, subject-relative)', '');
table(['lens', 'needs'], Object.keys(GENERIC_LENSES).map((id) => [`\`${id}\``, LENS_SUBJECTS[id].at ? '`lens:a>b`' : '`lens:subject`']));
L.push('Moves (stack any): ' + MOVE_IDS.map((m) => `\`${m}\``).join(', ') + '. Tokens `left`/`right` pick the side, `x1.5` scales moves.', '');
L.push('## Actions', '');
table(['action', 'what it does'], Object.entries(ACTIONS).map(([id, a]) => [`\`${id}\``, a.summary]));
L.push('## Looks', '');
table(['look', 'wardrobe'], Object.entries(LOOKS).map(([id, l]) => [`\`${id}\``, l.summary]));
L.push('## Transitions', '');
table(['type', 'default s', 'what it does'], Object.entries(TRANSITIONS).map(([id, t]) => [`\`${id}\``, String(t.duration), t.summary + (t.from ? ` (needs \`from\`: ${t.from})` : '') + (t.to ? ` (needs \`to\`: ${t.to})` : '')]));
L.push('## Effects', '');
table(['effect', 'layer', 'what it does'], Object.entries(EFFECTS).map(([id, e]) => [`\`${id}\``, e.layer + (e.worlds ? ` (${e.worlds.join(', ')})` : ''), e.summary]));
L.push('## Graphics', '');
table(['kind', 'props', 'what it does'], Object.entries(GRAPHICS).map(([id, g]) => [`\`${id}\``, Object.keys(g.props).map((p) => `\`${p}\``).join(', '), g.summary + (g.worlds ? ` (${g.worlds.join(', ')} only)` : '')]));
L.push('## Text styles', '');
table(['style', 'look'], Object.entries(TEXT_STYLES).map(([id, s]) => [`\`${id}\``, s]));
L.push('Placement: `top`, `upper`, `center`, `lower`, `bottom`, or `on:<subject>` (pinned to a world subject).', '');
L.push('## Sound cues', '');
table(['cue', 'source', 'what it is'], Object.entries(CUES).map(([id, c]) => [`\`${id}\``, c.source, c.summary]));
const out = path.join(REELS_ROOT, 'docs/VOCABULARY.md');
writeFileSync(out, L.join('\n'));
console.log(out);
process.exit(0);
