#!/usr/bin/env tsx
/**
 * blender:export — regenerate canonical HNC interchange assets (GLB + baked
 * textures + manifest) from @floodlight/hnc-visuals. No Blender needed.
 *
 * The canonical factories run in headless Chromium so Canvas-painted
 * textures (shirt number, ball skin) are the real ones. Output is
 * GENERATED: never edit it; rerun this command after canonical changes.
 */
import { execFileSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { build } from 'esbuild';
import { chromium } from 'playwright';
import type { HncBrowserExport } from './src/browser-entry.ts';
import { glbImageBytes, materialImages, parseGlb, pngSize } from './src/glb.ts';
import { CANONICAL_SOURCES, GENERATED, MANIFEST, REPO_ROOT, insideRepo, rel } from './src/paths.ts';

const sha256 = (b: Buffer | string): string => createHash('sha256').update(b).digest('hex');
const git = (...args: string[]): string => execFileSync('git', args, { cwd: REPO_ROOT, encoding: 'utf8' }).trim();

async function bundleBrowserEntry(): Promise<string> {
  const result = await build({
    entryPoints: [path.join(REPO_ROOT, 'tools/blender/src/browser-entry.ts')],
    bundle: true,
    format: 'iife',
    platform: 'browser',
    target: 'es2022',
    write: false,
    logLevel: 'warning',
  });
  return result.outputFiles[0].text;
}

async function runInBrowser(code: string): Promise<{ exports: HncBrowserExport[]; browser: string }> {
  const browser = await chromium.launch({ headless: true });
  try {
    const page = await browser.newPage();
    const errors: string[] = [];
    page.on('pageerror', (e) => errors.push(e.message));
    await page.setContent('<!doctype html><html><body></body></html>');
    await page.addScriptTag({ content: code });
    const exports = await page.evaluate(
      () => (globalThis as unknown as { hncExportAll: () => Promise<HncBrowserExport[]> }).hncExportAll(),
    );
    if (errors.length) throw new Error(`browser errors during export:\n${errors.join('\n')}`);
    return { exports, browser: `chromium ${browser.version()}` };
  } finally {
    await browser.close();
  }
}

async function main(): Promise<void> {
  const started = Date.now();
  const { exports, browser } = await runInBrowser(await bundleBrowserEntry());
  const assetsDir = insideRepo(path.join(GENERATED, 'hnc'));
  const texturesDir = insideRepo(path.join(GENERATED, 'textures'));
  mkdirSync(assetsDir, { recursive: true });
  mkdirSync(texturesDir, { recursive: true });

  const assets = exports.map((e) => {
    const glbBytes = Buffer.from(e.glbBase64, 'base64');
    const glbPath = path.join(assetsDir, `${e.assetId}.glb`);
    writeFileSync(glbPath, glbBytes);
    const glb = parseGlb(glbBytes);
    // Baked copies of every embedded texture, byte-identical to the GLB payload.
    const textures = materialImages(glb).map(({ material, image }) => {
      const png = glbImageBytes(glb, image);
      const file = path.join(texturesDir, `${e.assetId}--${material}.png`);
      writeFileSync(file, png);
      return { material, file: rel(file), ...pngSize(png), sha256: sha256(png) };
    });
    for (const m of e.expected.materials) {
      const baked = textures.find((t) => t.material === m.name);
      if (m.map && (!baked || baked.width !== m.map.width || baked.height !== m.map.height)) {
        throw new Error(`${e.assetId}: texture for ${m.name} missing or resized in GLB`);
      }
    }
    return {
      assetId: e.assetId,
      purpose: e.purpose,
      sourceFactory: e.sourceFactory,
      params: e.params,
      glb: rel(glbPath),
      sha256: sha256(glbBytes),
      bytes: glbBytes.length,
      generator: glb.json.asset.generator ?? null,
      textures,
      expected: e.expected,
    };
  });

  const sources = CANONICAL_SOURCES.map((p) => ({ path: p, sha256: sha256(readFileSync(path.join(REPO_ROOT, p))) }));
  const dirtySources = git('status', '--porcelain', '--', ...CANONICAL_SOURCES).split('\n').filter(Boolean);
  const manifest = {
    schema: 'hnc-blender-manifest/1',
    note: 'GENERATED by `npm run blender:export` — do not edit. Timestamps are provenance only; rendering never reads them.',
    generatedAt: new Date().toISOString(),
    git: { head: git('rev-parse', 'HEAD'), branch: git('branch', '--show-current'), dirtyCanonicalSources: dirtySources },
    toolchain: {
      three: JSON.parse(readFileSync(path.join(REPO_ROOT, 'node_modules/three/package.json'), 'utf8')).version,
      browser,
      exporter: 'three/examples/jsm/exporters/GLTFExporter (binary, trs, onlyVisible)',
    },
    interchange: {
      units: 'metres',
      hncAndGlb: 'right-handed, +Y up, asset front +Z (identity — the exporter applies no transform)',
      blender: 'glTF importer converts (x, y, z) -> (x, -z, y): +Z up, character faces -Y',
      flatShading: 'NORMAL omitted on flat-shaded parts → Blender marks those faces sharp',
      excluded: ['player.shadow and ball.shadow blob decals (game-only fakes; Blender renders real shadows)'],
    },
    sources,
    assets,
  };
  writeFileSync(insideRepo(MANIFEST), `${JSON.stringify(manifest, null, 2)}\n`);

  for (const a of assets) {
    console.log(`${a.assetId}: ${a.glb} (${a.bytes} B, sha256 ${a.sha256.slice(0, 12)}…, ${a.textures.length} texture(s))`);
  }
  console.log(`manifest: ${rel(MANIFEST)} — ${browser} — ${Date.now() - started} ms`);
}

main().catch((e: unknown) => {
  console.error(e instanceof Error ? e.message : e);
  process.exit(1);
});
